//! # LLM Provider Abstraction
//!
//! Pluggable LLM backend layer. All agent code calls the [`LlmProvider`] trait,
//! never a concrete HTTP client directly.
//!
//! ## Supported providers
//!
//! | Module        | Provider                              |
//! |---------------|---------------------------------------|
//! | [`openai`]    | OpenAI (GPT-4o, GPT-4-turbo, etc.)   |
//! | [`anthropic`] | Anthropic (Claude 3.5 Sonnet, etc.)  |

pub mod anthropic;
pub mod openai_compatible;

use async_trait::async_trait;
use futures::Stream;
use serde::{Deserialize, Serialize};
use std::pin::Pin;
use thiserror::Error;

// ──────────────────────────────────────────────
// Message types
// ──────────────────────────────────────────────

/// Role of a message in a conversation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MessageRole {
    System,
    User,
    Assistant,
    /// Carries the result of a tool call back to the model.
    Tool,
}

/// A single message in an LLM conversation.
///
/// The `tool_calls` and `tool_result` fields are only populated for the special
/// assistant / tool roles used during function-calling turns.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmMessage {
    pub role: MessageRole,
    /// Text content. Empty for assistant messages that only contain tool calls.
    pub content: String,
    /// Set when `role == Assistant` and the model returned tool invocations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Set when `role == Tool` — identifies the tool call this result answers.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    /// Whether this tool result represents an error.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_error: Option<bool>,
}

impl LlmMessage {
    pub fn system(content: impl Into<String>) -> Self {
        Self { role: MessageRole::System, content: content.into(), tool_calls: None, tool_call_id: None, is_error: None }
    }

    pub fn user(content: impl Into<String>) -> Self {
        Self { role: MessageRole::User, content: content.into(), tool_calls: None, tool_call_id: None, is_error: None }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Self { role: MessageRole::Assistant, content: content.into(), tool_calls: None, tool_call_id: None, is_error: None }
    }

    /// Assistant message that carries tool call requests (no text content).
    pub fn assistant_tool_calls(calls: Vec<ToolCall>) -> Self {
        Self { role: MessageRole::Assistant, content: String::new(), tool_calls: Some(calls), tool_call_id: None, is_error: None }
    }

    /// Tool result message returned to the model after executing a tool call.
    pub fn tool_result(tool_call_id: impl Into<String>, content: impl Into<String>, is_error: bool) -> Self {
        Self {
            role: MessageRole::Tool,
            content: content.into(),
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
            is_error: Some(is_error),
        }
    }
}

// ──────────────────────────────────────────────
// Tool types
// ──────────────────────────────────────────────

/// JSON-Schema description of a tool that agents can invoke.
///
/// This is the provider-agnostic definition.  Each [`LlmProvider`] implementation
/// translates it into the wire format expected by its API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolDef {
    pub name: String,
    pub description: String,
    /// JSON Schema object describing the tool's parameters.
    pub parameters: serde_json::Value,
}

/// A single tool invocation requested by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Opaque ID generated by the model; used to pair results with requests.
    pub id: String,
    pub name: String,
    /// Parsed arguments (the model produces JSON matching `ToolDef::parameters`).
    pub arguments: serde_json::Value,
}

/// The result of a [`LlmProvider::complete_with_tools`] call.
#[derive(Debug)]
pub enum LlmCompletion {
    /// The model produced a final text response — the tool loop is finished.
    Done {
        text: String,
        prompt_tokens: Option<u32>,
        completion_tokens: Option<u32>,
    },
    /// The model wants to invoke one or more tools before continuing.
    NeedTools {
        calls: Vec<ToolCall>,
        prompt_tokens: Option<u32>,
        completion_tokens: Option<u32>,
    },
}

// ──────────────────────────────────────────────
// Response types
// ──────────────────────────────────────────────

/// A complete (non-streaming) response from the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    pub content: String,
    pub model: String,
    /// Tokens consumed by the prompt / system + user messages.
    pub prompt_tokens: Option<u32>,
    /// Tokens generated in the completion.
    pub completion_tokens: Option<u32>,
    /// Total tokens (prompt + completion).  Derived if both parts are known.
    pub total_tokens: Option<u32>,
}

/// A single chunk emitted during a streaming LLM response.
#[derive(Debug, Clone)]
pub struct StreamChunk {
    /// Incremental text delta.
    pub delta: String,
    /// `true` on the final chunk — the stream is complete.
    pub finished: bool,
}

// ──────────────────────────────────────────────
// Error type
// ──────────────────────────────────────────────

#[derive(Debug, Error)]
pub enum LlmError {
    #[error("HTTP request failed: {0}")]
    Http(#[from] reqwest::Error),

    #[error("API error (status {status}): {message}")]
    Api { status: u16, message: String },

    #[error("Missing API key for provider '{provider}'. Set the {env_var} environment variable.")]
    MissingApiKey {
        provider: &'static str,
        env_var: &'static str,
    },

    #[error("Failed to parse LLM response: {0}")]
    Parse(String),

    #[error("Streaming error: {0}")]
    Stream(String),
}

impl LlmError {
    /// Returns `true` if this error is a network request timeout.
    pub fn is_timeout(&self) -> bool {
        matches!(self, LlmError::Http(e) if e.is_timeout())
    }

    /// Returns `true` if this is a connection-level network error.
    pub fn is_connect(&self) -> bool {
        matches!(self, LlmError::Http(e) if e.is_connect())
    }

    /// Categorise the error for observability and user-facing display.
    pub fn error_category(&self) -> &'static str {
        match self {
            LlmError::Http(e) if e.is_timeout() => "request_timeout",
            LlmError::Http(e) if e.is_connect() => "connection_error",
            LlmError::Http(_) => "network_error",
            LlmError::Api { status, .. } if *status == 429 => "rate_limited",
            LlmError::Api { status, .. } if *status >= 500 => "server_error",
            LlmError::Api { .. } => "api_error",
            LlmError::MissingApiKey { .. } => "missing_api_key",
            LlmError::Parse(_) => "parse_error",
            LlmError::Stream(_) => "stream_error",
        }
    }

    /// Human-readable message suitable for end-user display.
    pub fn user_message(&self) -> String {
        match self {
            LlmError::Http(e) if e.is_timeout() =>
                "LLM 请求超时 — 模型服务器未在规定时间内响应，请检查网络连接或稍后重试。".into(),
            LlmError::Http(e) if e.is_connect() =>
                format!("无法连接到 LLM 服务器 — 请检查网络和 API 端点配置。({})", e),
            LlmError::Http(e) =>
                format!("LLM 请求网络错误: {}", e),
            LlmError::Api { status: 429, message } =>
                format!("API 请求频率超限，请稍后重试。({})", message),
            LlmError::Api { status, message } if *status >= 500 =>
                format!("LLM 服务器错误 (HTTP {}): {}", status, message),
            LlmError::Api { status, message } =>
                format!("API 错误 (HTTP {}): {}", status, message),
            other => other.to_string(),
        }
    }
}

// ──────────────────────────────────────────────
// Provider trait
// ──────────────────────────────────────────────

/// A pinned, boxed async stream of [`StreamChunk`] results.
pub type ChunkStream = Pin<Box<dyn Stream<Item = Result<StreamChunk, LlmError>> + Send>>;

/// Every LLM backend must implement this trait.
#[async_trait]
pub trait LlmProvider: Send + Sync {
    /// The provider identifier (e.g. `"openai"`, `"anthropic"`).
    fn provider_name(&self) -> &str;

    /// The model name in use (e.g. `"gpt-4o"`, `"claude-3-5-sonnet-20241022"`).
    fn model_name(&self) -> &str;

    /// Send a list of messages and await the full response.
    async fn complete(&self, messages: &[LlmMessage]) -> Result<LlmResponse, LlmError>;

    /// Send a list of messages and receive the response as a streaming sequence of chunks.
    async fn stream(&self, messages: &[LlmMessage]) -> Result<ChunkStream, LlmError>;

    /// Send messages together with available tool definitions.
    ///
    /// Returns [`LlmCompletion::Done`] when the model has produced its final
    /// answer, or [`LlmCompletion::NeedTools`] when it wants to invoke tools
    /// before continuing.  The caller is responsible for executing the tools,
    /// appending the results via [`LlmMessage::tool_result`], and calling this
    /// method again until `Done` is returned.
    async fn complete_with_tools(
        &self,
        messages: &[LlmMessage],
        tools: &[ToolDef],
    ) -> Result<LlmCompletion, LlmError>;
}
